stream:
  # WebSockets (wss://) Ethereum EVM endpoint
  provider: wss://mainnet.infura.io/ws/v3/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
payments:
  # Only localhost and clients from these IP addresses will be allowed to add
  # payments.
  # e.g.: ["8.8.8.8", "9.9.9.9"]
  ip_whitelist: []
  port: 8888
payments_worker:
  # HTTP Ethereum EVM endpoint
  provider: https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  every: 60
  threads: 10
